import Head from 'next/head';
import { Inter } from 'next/font/google';
import YandexMetrika from './YandexMetrika';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Head>
        <YandexMetrika
          yid={process.env.YANDEX_METRIKA_ID}
          clickmap={true}
          trackLinks={true}
          accurateTrackBounce={true}
          webvisor={true}
        />
      </Head>
      <div className={inter.className}>{children}</div>
    </>
  );
}